// LGS 8. Sınıf Tüm Konular - Veri Dosyası
const courseData = {
    math: {
        topics: [
            { id: "carpanlar-katlar", title: "1. Çarpanlar ve Katlar", content: { lecture: `<h2>Çarpanlar ve Katlar</h2><p>EBOB ve EKOK konuları.</p>`, summary: `<h2>Özet</h2><p>EBOB: Bölen, EKOK: Kat</p>`, tips: `<h2>İpucu</h2><p>Parçalama EBOB, birleştirme EKOK</p>`, mistakes: `<h2>Dikkat</h2><p>1 asal değildir</p>`, questions: [{ id: 1, text: "24 ve 36'nın EBOB'u?", options: ["6", "12", "18", "24"], correct: 1 }], game: { type: "matching", pairs: [{ text: "EBOB", match: "Bölen" }, { text: "EKOK", match: "Kat" }] } } },
            { id: "uslu-ifadeler", title: "2. Üslü İfadeler", content: { lecture: `<h2>Üslü İfadeler</h2><p>Üslü sayılarla işlemler</p>`, summary: `<h2>Özet</h2><p>Tabanlar aynıysa üsler toplanır</p>`, tips: `<h2>İpucu</h2><p>Negatif üs ters çevirir</p>`, mistakes: `<h2>Dikkat</h2><p>(-2)^4 ≠ -2^4</p>`, questions: [{ id: 11, text: "2^-3 kaçtır?", options: ["-8", "1/8", "-1/8", "8"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Negatif Üs", match: "Ters Çevir" }] } } },
            { id: "karekoklu-ifadeler", title: "3. Kareköklü İfadeler", content: { lecture: `<h2>Kareköklü İfadeler</h2><p>Tam kare sayılar</p>`, summary: `<h2>Özet</h2><p>√144 = 12</p>`, tips: `<h2>İpucu</h2><p>Kök dışına çıkarma</p>`, mistakes: `<h2>Dikkat</h2><p>√a + √b ≠ √(a+b)</p>`, questions: [{ id: 21, text: "√144 kaçtır?", options: ["10", "12", "14", "16"], correct: 1 }], game: { type: "matching", pairs: [{ text: "√100", match: "10" }] } } },
            { id: "veri-analizi", title: "4. Veri Analizi", content: { lecture: `<h2>Veri Analizi</h2><p>Grafikler</p>`, summary: `<h2>Özet</h2><p>Daire grafiği 360°</p>`, tips: `<h2>İpucu</h2><p>Oran-orantı</p>`, mistakes: `<h2>Dikkat</h2><p>Toplam sayıya dikkat</p>`, questions: [{ id: 31, text: "%25 kaç derece?", options: ["45", "90", "120", "180"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Daire", match: "360°" }] } } },
            { id: "basit-olaylar", title: "5. Olasılık", content: { lecture: `<h2>Olasılık</h2><p>İstenilen/Tüm</p>`, summary: `<h2>Özet</h2><p>0 ile 1 arası</p>`, tips: `<h2>İpucu</h2><p>Kesin olay 1</p>`, mistakes: `<h2>Dikkat</h2><p>1'den büyük olamaz</p>`, questions: [{ id: 41, text: "Zarda 7 gelme olasılığı?", options: ["0", "1/6", "1", "1/2"], correct: 0 }], game: { type: "matching", pairs: [{ text: "İmkansız", match: "0" }] } } },
            { id: "cebirsel-ifadeler", title: "6. Cebirsel İfadeler", content: { lecture: `<h2>Cebirsel İfadeler</h2><p>Özdeşlikler</p>`, summary: `<h2>Özet</h2><p>(a+b)² = a²+2ab+b²</p>`, tips: `<h2>İpucu</h2><p>Ortadaki 2ab</p>`, mistakes: `<h2>Dikkat</h2><p>(a+b)² ≠ a²+b²</p>`, questions: [{ id: 51, text: "(x+3)² açılımı?", options: ["x²+9", "x²+3x+9", "x²+6x+9", "x²+9x+9"], correct: 2 }], game: { type: "matching", pairs: [{ text: "İki Kare Farkı", match: "a²-b²" }] } } },
            { id: "dogrusal-denklemler", title: "7. Doğrusal Denklemler", content: { lecture: `<h2>Doğrusal Denklemler</h2><p>Eğim</p>`, summary: `<h2>Özet</h2><p>y = mx + n</p>`, tips: `<h2>İpucu</h2><p>m eğimdir</p>`, mistakes: `<h2>Dikkat</h2><p>Orijinden geçen y=mx</p>`, questions: [{ id: 61, text: "y=3x+5 eğimi?", options: ["3", "5", "-3", "1/3"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Eğim", match: "m" }] } } },
            { id: "esitsizlikler", title: "8. Eşitsizlikler", content: { lecture: `<h2>Eşitsizlikler</h2><p>Yön değişimi</p>`, summary: `<h2>Özet</h2><p>Negatifle çarpınca yön değişir</p>`, tips: `<h2>İpucu</h2><p>Sayı doğrusu</p>`, mistakes: `<h2>Dikkat</h2><p>Yön değiştirmeyi unutma</p>`, questions: [{ id: 71, text: "-2x<10 çözümü?", options: ["x<-5", "x>-5", "x<5", "x>5"], correct: 1 }], game: { type: "matching", pairs: [{ text: "<", match: "Küçüktür" }] } } },
            { id: "ucgenler", title: "9. Üçgenler", content: { lecture: `<h2>Üçgenler</h2><p>Pisagor</p>`, summary: `<h2>Özet</h2><p>a²+b²=c²</p>`, tips: `<h2>İpucu</h2><p>Dik üçgen</p>`, mistakes: `<h2>Dikkat</h2><p>En uzun kenar hipotenüs</p>`, questions: [{ id: 81, text: "3,4,? hipotenüs?", options: ["5", "6", "7", "8"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Pisagor", match: "a²+b²=c²" }] } } },
            { id: "eslik-benzerlik", title: "10. Eşlik ve Benzerlik", content: { lecture: `<h2>Eşlik ve Benzerlik</h2><p>Benzerlik oranı</p>`, summary: `<h2>Özet</h2><p>Alan oranı k²</p>`, tips: `<h2>İpucu</h2><p>Tales teoremi</p>`, mistakes: `<h2>Dikkat</h2><p>Eş şekil k=1</p>`, questions: [{ id: 91, text: "k=1/2, alan oranı?", options: ["1/2", "1/4", "1/8", "2"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Eşlik", match: "k=1" }] } } },
            { id: "donusum-geometrisi", title: "11. Dönüşüm Geometrisi", content: { lecture: `<h2>Dönüşüm Geometrisi</h2><p>Öteleme, Yansıma</p>`, summary: `<h2>Özet</h2><p>X eksenine yansıma y değişir</p>`, tips: `<h2>İpucu</h2><p>Öteleme yer değiştirir</p>`, mistakes: `<h2>Dikkat</h2><p>Yansıma ters döner</p>`, questions: [{ id: 101, text: "(2,3) x eksenine yansıma?", options: ["(-2,3)", "(2,-3)", "(-2,-3)", "(3,2)"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Öteleme", match: "Yer" }] } } },
            { id: "geometrik-cisimler", title: "12. Geometrik Cisimler", content: { lecture: `<h2>Geometrik Cisimler</h2><p>Hacim formülleri</p>`, summary: `<h2>Özet</h2><p>Silindir: πr²h</p>`, tips: `<h2>İpucu</h2><p>Piramit/Koni 1/3</p>`, mistakes: `<h2>Dikkat</h2><p>Açık hal</p>`, questions: [{ id: 111, text: "r=3, h=4, π=3, hacim?", options: ["36", "72", "108", "144"], correct: 2 }], game: { type: "matching", pairs: [{ text: "Silindir", match: "πr²h" }] } } }
        ]
    },
    science: {
        topics: [
            { id: "mevsimler-iklim", title: "1. Mevsimler ve İklim", content: { lecture: `<h2>Mevsimler</h2><p>Eksen eğikliği</p>`, summary: `<h2>Özet</h2><p>21 Haziran, 21 Aralık</p>`, tips: `<h2>İpucu</h2><p>İklim geniş bölge</p>`, mistakes: `<h2>Dikkat</h2><p>Uzaklık değil eğiklik</p>`, questions: [{ id: 101, text: "En uzun gece (KYK)?", options: ["21 Haz", "21 Ara", "23 Eyl", "21 Mar"], correct: 1 }], game: { type: "matching", pairs: [{ text: "21 Haz", match: "Yaz" }] } } },
            { id: "dna-genetik", title: "2. DNA ve Genetik", content: { lecture: `<h2>DNA</h2><p>Nükleotid</p>`, summary: `<h2>Özet</h2><p>A=T, G=C</p>`, tips: `<h2>İpucu</h2><p>Büyük harf baskın</p>`, mistakes: `<h2>Dikkat</h2><p>Akraba evliliği risk</p>`, questions: [{ id: 111, text: "DNA yapı birimi?", options: ["Gen", "Nükleotid", "Kromozom", "Hücre"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Adenin", match: "Timin" }] } } },
            { id: "basinc", title: "3. Basınç", content: { lecture: `<h2>Basınç</h2><p>Katı, Sıvı, Gaz</p>`, summary: `<h2>Özet</h2><p>P=F/S</p>`, tips: `<h2>İpucu</h2><p>Sıvı şekle bağlı değil</p>`, mistakes: `<h2>Dikkat</h2><p>Pascal prensibi</p>`, questions: [{ id: 121, text: "Sıvı basıncı neye bağlı?", options: ["Alan", "Derinlik", "Şekil", "Renk"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Pascal", match: "Sıvı" }] } } },
            { id: "madde-endustri", title: "4. Madde ve Endüstri", content: { lecture: `<h2>Madde</h2><p>Periyodik tablo</p>`, summary: `<h2>Özet</h2><p>pH<7 asit</p>`, tips: `<h2>İpucu</h2><p>Metal elektron verir</p>`, mistakes: `<h2>Dikkat</h2><p>Kütle korunur</p>`, questions: [{ id: 131, text: "pH=2 nedir?", options: ["Asit", "Baz", "Nötr", "Tuz"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Asit", match: "Ekşi" }] } } },
            { id: "basit-makineler", title: "5. Basit Makineler", content: { lecture: `<h2>Basit Makineler</h2><p>Makaralar</p>`, summary: `<h2>Özet</h2><p>İşten kazanç yok</p>`, tips: `<h2>İpucu</h2><p>Hareketli makara 2 kat</p>`, mistakes: `<h2>Dikkat</h2><p>İş kolaylığı</p>`, questions: [{ id: 141, text: "Kuvvet kazancı kesin?", options: ["Sabit", "Hareketli", "Tahterevalli", "Makas"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Sabit", match: "Yön" }] } } },
            { id: "enerji-donusumleri", title: "6. Enerji Dönüşümleri", content: { lecture: `<h2>Enerji</h2><p>Fotosentez</p>`, summary: `<h2>Özet</h2><p>Işık+CO2+Su→Besin+O2</p>`, tips: `<h2>İpucu</h2><p>Mantar ayrıştırıcı</p>`, mistakes: `<h2>Dikkat</h2><p>Fotosentez gündüz</p>`, questions: [{ id: 151, text: "Fotosentez nerede?", options: ["Mitokondri", "Kloroplast", "Koful", "Çekirdek"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Üretici", match: "Bitki" }] } } },
            { id: "elektrik-yukleri", title: "7. Elektrik Yükleri", content: { lecture: `<h2>Elektrik</h2><p>Elektriklenme</p>`, summary: `<h2>Özet</h2><p>Aynı iter, zıt çeker</p>`, tips: `<h2>İpucu</h2><p>Sürtünme zıt yükler</p>`, mistakes: `<h2>Dikkat</h2><p>Proton hareket etmez</p>`, questions: [{ id: 161, text: "Pozitif nötrü ne yapar?", options: ["İter", "Çeker", "Etkilemez", "Nötrler"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Aynı", match: "İter" }] } } }
        ]
    },
    turkish: {
        topics: [
            { id: "sozcukte-anlam", title: "1. Sözcükte Anlam", content: { lecture: `<h2>Sözcükte Anlam</h2><p>Gerçek, Mecaz</p>`, summary: `<h2>Özet</h2><p>Gerçek ilk akla gelen</p>`, tips: `<h2>İpucu</h2><p>Cümleye bakma</p>`, mistakes: `<h2>Dikkat</h2><p>Boş kutu gerçek</p>`, questions: [{ id: 191, text: "Ağır hangisinde mecaz?", options: ["Çanta", "Sözler", "Masa", "Taş"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Mecaz", match: "Soyut" }] } } },
            { id: "cumlede-anlam", title: "2. Cümlede Anlam", content: { lecture: `<h2>Cümlede Anlam</h2><p>Neden-Sonuç</p>`, summary: `<h2>Özet</h2><p>Amaç: için</p>`, tips: `<h2>İpucu</h2><p>Amacıyla testi</p>`, mistakes: `<h2>Dikkat</h2><p>Neden gerçekleşmiş</p>`, questions: [{ id: 192, text: "Amaç-sonuç?", options: ["Yağdığı için", "Görmek için", "Çalışırsan", "Çok sıcak"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Amaç", match: "Hedef" }] } } },
            { id: "paragrafta-anlam", title: "3. Paragrafta Anlam", content: { lecture: `<h2>Paragrafta Anlam</h2><p>Ana düşünce</p>`, summary: `<h2>Özet</h2><p>Yazarın mesajı</p>`, tips: `<h2>İpucu</h2><p>Genelde son cümle</p>`, mistakes: `<h2>Dikkat</h2><p>Dışına çıkma</p>`, questions: [{ id: 193, text: "Yazarın mesajı?", options: ["Konu", "Başlık", "Ana Düşünce", "Giriş"], correct: 2 }], game: { type: "matching", pairs: [{ text: "Betimleme", match: "Resim" }] } } },
            { id: "soz-gruplarinda-anlam", title: "4. Söz Gruplarında Anlam", content: { lecture: `<h2>Söz Grupları</h2><p>Deyimler</p>`, summary: `<h2>Özet</h2><p>Deyim mecaz</p>`, tips: `<h2>İpucu</h2><p>Atasözü öğüt</p>`, mistakes: `<h2>Dikkat</h2><p>Eli açık cömert</p>`, questions: [{ id: 194, text: "Hangisi deyim?", options: ["Damlaya damlaya", "Ağzı kulaklarında", "Yavaş yavaş", "Güzel güzel"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Deyim", match: "Mecaz" }] } } },
            { id: "anlatim-bozukluklari", title: "5. Anlatım Bozuklukları", content: { lecture: `<h2>Anlatım Bozuklukları</h2><p>Gereksiz tekrar</p>`, summary: `<h2>Özet</h2><p>Özne-yüklem uyumu</p>`, tips: `<h2>İpucu</h2><p>Geri dönmek doğru</p>`, mistakes: `<h2>Dikkat</h2><p>Kitabı okudum onu yanlış</p>`, questions: [{ id: 195, text: "Bozukluk var?", options: ["Eve gittim", "Kitap okuyorum", "Geri geri döndü", "Çok güzel"], correct: 2 }], game: { type: "matching", pairs: [{ text: "Tekrar", match: "Bozukluk" }] } } },
            { id: "gorsel-okuma", title: "6. Görsel Okuma", content: { lecture: `<h2>Görsel Okuma</h2><p>Görselleri anlama</p>`, summary: `<h2>Özet</h2><p>Mesajı anlama</p>`, tips: `<h2>İpucu</h2><p>Renk, şekil, boyut</p>`, mistakes: `<h2>Dikkat</h2><p>Olmayan ekleme</p>`, questions: [{ id: 196, text: "En önemli unsur?", options: ["Renk", "Mesaj", "Boyut", "Çerçeve"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Afiş", match: "Tanıtım" }] } } },
            { id: "fiilimsiler", title: "7. Fiilimsiler", content: { lecture: `<h2>Fiilimsiler</h2><p>İsim-fiil</p>`, summary: `<h2>Özet</h2><p>Mayışmak</p>`, tips: `<h2>İpucu</h2><p>Yan cümlecik</p>`, mistakes: `<h2>Dikkat</h2><p>Kalıcı isim değil</p>`, questions: [{ id: 201, text: "Sıfat-fiil?", options: ["Gelmiş", "Gelen", "Gelip", "Gelmek"], correct: 1 }], game: { type: "matching", pairs: [{ text: "İsim Fiil", match: "-ma" }] } } },
            { id: "cumlenin-ogeleri", title: "8. Cümlenin Ögeleri", content: { lecture: `<h2>Cümlenin Ögeleri</h2><p>Yüklem, Özne</p>`, summary: `<h2>Özet</h2><p>YÖN kuralı</p>`, tips: `<h2>İpucu</h2><p>Söz öbekleri ayrılmaz</p>`, mistakes: `<h2>Dikkat</h2><p>Hitap öge değil</p>`, questions: [{ id: 211, text: "İşi yapan?", options: ["Nesne", "Özne", "Yüklem", "Zarf"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Yüklem", match: "Yargı" }] } } },
            { id: "fiilde-cati", title: "9. Fiilde Çatı", content: { lecture: `<h2>Fiilde Çatı</h2><p>Etken, Edilgen</p>`, summary: `<h2>Özet</h2><p>Etken özne belli</p>`, tips: `<h2>İpucu</h2><p>Onu testi</p>`, mistakes: `<h2>Dikkat</h2><p>İsim cümlesinde yok</p>`, questions: [{ id: 221, text: "Geçişli fiil?", options: ["Uyudu", "Baktı", "Okudu", "Durdu"], correct: 2 }], game: { type: "matching", pairs: [{ text: "Etken", match: "Gerçek Özne" }] } } },
            { id: "cumle-turleri", title: "10. Cümle Türleri", content: { lecture: `<h2>Cümle Türleri</h2><p>Basit, Birleşik</p>`, summary: `<h2>Özet</h2><p>Fiilimsi birleşik</p>`, tips: `<h2>İpucu</h2><p>Girişik birleşik</p>`, mistakes: `<h2>Dikkat</h2><p>Devrik yüklem sonda değil</p>`, questions: [{ id: 231, text: "Fiilimsi yapısı?", options: ["Basit", "Birleşik", "Sıralı", "Bağlı"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Basit", match: "Tek Yargı" }] } } },
            { id: "yazim-noktalama", title: "11. Yazım ve Noktalama", content: { lecture: `<h2>Yazım</h2><p>Büyük harf</p>`, summary: `<h2>Özet</h2><p>Özel isim büyük</p>`, tips: `<h2>İpucu</h2><p>Ler eki testi</p>`, mistakes: `<h2>Dikkat</h2><p>Kurum eki kesme yok</p>`, questions: [{ id: 241, text: "Yanlış yazım?", options: ["TDK'nin", "TBMM'ye", "Ahmet'ler", "Ankara'da"], correct: 2 }], game: { type: "matching", pairs: [{ text: "Nokta", match: "Bitmiş" }] } } },
            { id: "metin-turleri", title: "12. Metin Türleri", content: { lecture: `<h2>Metin Türleri</h2><p>Makale, Deneme</p>`, summary: `<h2>Özet</h2><p>Makale nesnel</p>`, tips: `<h2>İpucu</h2><p>Mübalağa abartma</p>`, mistakes: `<h2>Dikkat</h2><p>Fıkra köşe yazısı</p>`, questions: [{ id: 251, text: "Kanıtlama?", options: ["Deneme", "Makale", "Söyleşi", "Günlük"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Makale", match: "Nesnel" }] } } },
            { id: "sozel-mantik", title: "13. Sözel Mantık", content: { lecture: `<h2>Sözel Mantık</h2><p>Tablo</p>`, summary: `<h2>Özet</h2><p>Tablo çiz</p>`, tips: `<h2>İpucu</h2><p>Kesin olanlar</p>`, mistakes: `<h2>Dikkat</h2><p>Olabilir vs Kesinlikle</p>`, questions: [{ id: 261, text: "En önemli yöntem?", options: ["Hızlı okuma", "Tablo çizme", "Ezberleme", "Şık eleme"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Tablo", match: "Çözüm" }] } } }
        ]
    },
    history: {
        topics: [
            { id: "bir-kahraman", title: "1. Bir Kahraman Doğuyor", content: { lecture: `<h2>Bir Kahraman</h2><p>M.Kemal</p>`, summary: `<h2>Özet</h2><p>Selanik</p>`, tips: `<h2>İpucu</h2><p>Fikir akımları</p>`, mistakes: `<h2>Dikkat</h2><p>Şam'da Vatan ve Hürriyet</p>`, questions: [{ id: 301, text: "Doğum yeri?", options: ["Selanik", "Manastır", "İstanbul", "Sofya"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Selanik", match: "Doğum" }] } } },
            { id: "milli-uyanis", title: "2. Milli Uyanış", content: { lecture: `<h2>Milli Uyanış</h2><p>I. Dünya Savaşı</p>`, summary: `<h2>Özet</h2><p>Mondros 7-24</p>`, tips: `<h2>İpucu</h2><p>Sivas Kongresi</p>`, mistakes: `<h2>Dikkat</h2><p>Kuvayi Milliye düzensiz</p>`, questions: [{ id: 311, text: "İşgal maddesi?", options: ["7", "24", "1", "10"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Mondros", match: "İşgal" }] } } },
            { id: "ya-istiklal", title: "3. Ya İstiklal Ya Ölüm", content: { lecture: `<h2>Ya İstiklal</h2><p>Cepheler</p>`, summary: `<h2>Özet</h2><p>Doğu, Güney, Batı</p>`, tips: `<h2>İpucu</h2><p>İlk Doğu, son Batı</p>`, mistakes: `<h2>Dikkat</h2><p>Sakarya Subaylar Savaşı</p>`, questions: [{ id: 321, text: "İlk siyasi başarı?", options: ["Gümrü", "Moskova", "Ankara", "Kars"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Doğu", match: "K.Karabekir" }] } } },
            { id: "ataturkculuk", title: "4. Atatürkçülük", content: { lecture: `<h2>Atatürkçülük</h2><p>İlkeler</p>`, summary: `<h2>Özet</h2><p>6 ok</p>`, tips: `<h2>İpucu</h2><p>Akıl-bilim Laiklik</p>`, mistakes: `<h2>Dikkat</h2><p>Saltanat ilk adım</p>`, questions: [{ id: 331, text: "Din-devlet ayrımı?", options: ["Laiklik", "Halkçılık", "Devletçilik", "İnkılapçılık"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Cumhuriyetçilik", match: "Seçim" }] } } },
            { id: "demokratiklesme", title: "5. Demokratikleşme", content: { lecture: `<h2>Demokratikleşme</h2><p>Çok parti</p>`, summary: `<h2>Özet</h2><p>Terakkiperver, Serbest</p>`, tips: `<h2>İpucu</h2><p>İsyanlar erteledi</p>`, mistakes: `<h2>Dikkat</h2><p>M.Kemal CHP kurdu</p>`, questions: [{ id: 341, text: "İlk muhalefet?", options: ["Terakkiperver", "Serbest", "Demokrat", "Milli"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Şeyh Sait", match: "İsyan" }] } } },
            { id: "dis-politika", title: "6. Dış Politika", content: { lecture: `<h2>Dış Politika</h2><p>Musul, Hatay</p>`, summary: `<h2>Özet</h2><p>Hatay 1939</p>`, tips: `<h2>İpucu</h2><p>Montrö Boğazlar</p>`, mistakes: `<h2>Dikkat</h2><p>Musul taviz</p>`, questions: [{ id: 351, text: "Hatay ne zaman?", options: ["1938", "1939", "1930", "1923"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Montrö", match: "Boğazlar" }] } } },
            { id: "ataturk-olumu", title: "7. Atatürk'ün Ölümü", content: { lecture: `<h2>Ölüm</h2><p>10 Kasım 1938</p>`, summary: `<h2>Özet</h2><p>II. Dünya Savaşı</p>`, tips: `<h2>İpucu</h2><p>Fiilen girmedi</p>`, mistakes: `<h2>Dikkat</h2><p>Önce Etnografya</p>`, questions: [{ id: 361, text: "Vefat yeri?", options: ["Dolmabahçe", "Çankaya", "Topkapı", "Yıldız"], correct: 0 }], game: { type: "matching", pairs: [{ text: "1938", match: "Vefat" }] } } }
        ]
    },
    english: {
        topics: [
            { id: "friendship", title: "1. Friendship", content: { lecture: `<h2>Friendship</h2><p>Invitations</p>`, summary: `<h2>Summary</h2><p>Buddy, Mate</p>`, tips: `<h2>Tips</h2><p>Would you like?</p>`, mistakes: `<h2>Attention</h2><p>Stubborn=Obstinate</p>`, questions: [{ id: 401, text: "Synonym Trust?", options: ["Count on", "Lie", "Refuse", "Argue"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Buddy", match: "Friend" }] } } },
            { id: "teen-life", title: "2. Teen Life", content: { lecture: `<h2>Teen Life</h2><p>Routines</p>`, summary: `<h2>Summary</h2><p>Prefer, Keen on</p>`, tips: `<h2>Tips</h2><p>Prefer Ving to Ving</p>`, mistakes: `<h2>Attention</h2><p>Ridiculous=Silly</p>`, questions: [{ id: 411, text: "I prefer ___ music", options: ["listen", "listening", "listens", "to listen"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Keen on", match: "Like" }] } } },
            { id: "in-the-kitchen", title: "3. In The Kitchen", content: { lecture: `<h2>Kitchen</h2><p>Cooking</p>`, summary: `<h2>Summary</h2><p>Boil, Fry</p>`, tips: `<h2>Tips</h2><p>First, Then</p>`, mistakes: `<h2>Attention</h2><p>Recipe=Tarif</p>`, questions: [{ id: 421, text: "Hot oil?", options: ["Boil", "Fry", "Bake", "Steam"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Boil", match: "Haşlamak" }] } } },
            { id: "on-the-phone", title: "4. On The Phone", content: { lecture: `<h2>Phone</h2><p>Conversations</p>`, summary: `<h2>Summary</h2><p>Pick up, Hang up</p>`, tips: `<h2>Tips</h2><p>May I speak?</p>`, mistakes: `<h2>Attention</h2><p>Hang on=Hold on</p>`, questions: [{ id: 431, text: "Don't ___ phone", options: ["hang up", "pick up", "dial", "call"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Hold on", match: "Wait" }] } } },
            { id: "the-internet", title: "5. The Internet", content: { lecture: `<h2>Internet</h2><p>Safety</p>`, summary: `<h2>Summary</h2><p>Log in, Sign up</p>`, tips: `<h2>Tips</h2><p>Social networking</p>`, mistakes: `<h2>Attention</h2><p>Register=Sign up</p>`, questions: [{ id: 441, text: "Put file online?", options: ["Download", "Upload", "Login", "Search"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Download", match: "İndirmek" }] } } },
            { id: "adventures", title: "6. Adventures", content: { lecture: `<h2>Adventures</h2><p>Sports</p>`, summary: `<h2>Summary</h2><p>Paragliding, Bungee</p>`, tips: `<h2>Tips</h2><p>I would rather</p>`, mistakes: `<h2>Attention</h2><p>Amusing=Eğlenceli</p>`, questions: [{ id: 451, text: "Bridge rope?", options: ["Rafting", "Bungee", "Caving", "Surfing"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Helmet", match: "Kask" }] } } },
            { id: "tourism", title: "7. Tourism", content: { lecture: `<h2>Tourism</h2><p>Holiday</p>`, summary: `<h2>Summary</h2><p>All-inclusive</p>`, tips: `<h2>Tips</h2><p>Have you been?</p>`, mistakes: `<h2>Attention</h2><p>Souvenir=Hediyelik</p>`, questions: [{ id: 461, text: "Kings lived?", options: ["Mosque", "Palace", "Bridge", "Tower"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Ancient", match: "Old" }] } } },
            { id: "chores", title: "8. Chores", content: { lecture: `<h2>Chores</h2><p>Housework</p>`, summary: `<h2>Summary</h2><p>Mop, Dust</p>`, tips: `<h2>Tips</h2><p>Have to/Must</p>`, mistakes: `<h2>Attention</h2><p>Make bed=Düzeltmek</p>`, questions: [{ id: 471, text: "Floor water?", options: ["Dusting", "Mopping", "Ironing", "Vacuuming"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Laundry", match: "Çamaşır" }] } } },
            { id: "science", title: "9. Science", content: { lecture: `<h2>Science</h2><p>Inventions</p>`, summary: `<h2>Summary</h2><p>Lab, Experiment</p>`, tips: `<h2>Tips</h2><p>Process, Result</p>`, mistakes: `<h2>Attention</h2><p>Discover vs Invent</p>`, questions: [{ id: 481, text: "Create new?", options: ["Discover", "Invent", "Explore", "Search"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Lab", match: "Laboratuvar" }] } } },
            { id: "natural-forces", title: "10. Natural Forces", content: { lecture: `<h2>Natural Forces</h2><p>Disasters</p>`, summary: `<h2>Summary</h2><p>Earthquake, Tsunami</p>`, tips: `<h2>Tips</h2><p>Take precautions</p>`, mistakes: `<h2>Attention</h2><p>Drought=Kuraklık</p>`, questions: [{ id: 491, text: "Water on land?", options: ["Drought", "Flood", "Fire", "Storm"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Earthquake", match: "Deprem" }] } } }
        ]
    },
    religion: {
        topics: [
            { id: "kader", title: "1. Kader İnancı", content: { lecture: `<h2>Kader</h2><p>Sünnetullah</p><h3>Hz. Musa</h3><p>Firavun</p><h3>Ayet el-Kürsi</h3><p>Bakara 255</p>`, summary: `<h2>Özet</h2><p>Cüzi İrade</p>`, tips: `<h2>İpucu</h2><p>Tedbir bizden</p>`, mistakes: `<h2>Dikkat</h2><p>Sorumluluk</p>`, questions: [{ id: 501, text: "Allah'ın yasaları?", options: ["Sünnetullah", "Farz", "Vacip", "Sünnet"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Kader", match: "Ölçü" }] } } },
            { id: "zekat", title: "2. Zekat ve Sadaka", content: { lecture: `<h2>Zekat</h2><p>1/40</p><h3>Hz. Şuayb</h3><p>Ticaret ahlakı</p><h3>Maun Suresi</h3><p>Yetime yardım</p>`, summary: `<h2>Özet</h2><p>Nisab</p>`, tips: `<h2>İpucu</h2><p>Fitre Ramazan</p>`, mistakes: `<h2>Dikkat</h2><p>Anne-baba verilmez</p>`, questions: [{ id: 511, text: "Kalıcı sadaka?", options: ["Sadaka-i Cariye", "Fitre", "Zekat", "Fidye"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Zekat", match: "Farz" }] } } },
            { id: "din-hayat", title: "3. Din ve Hayat", content: { lecture: `<h2>Din ve Hayat</h2><p>Zarurat-ı Hamse</p><h3>Hz. Yusuf</h3><p>Sabır</p><h3>Asr Suresi</h3><p>Zaman</p>`, summary: `<h2>Özet</h2><p>Can, Mal, Akıl, Nesil, Din</p>`, tips: `<h2>İpucu</h2><p>İçki Akıl</p>`, mistakes: `<h2>Dikkat</h2><p>Kolaylık dini</p>`, questions: [{ id: 521, text: "İçki yasağı?", options: ["Can", "Mal", "Akıl", "Din"], correct: 2 }], game: { type: "matching", pairs: [{ text: "Nesil", match: "Aile" }] } } },
            { id: "hz-muhammed", title: "4. Hz. Muhammed", content: { lecture: `<h2>Hz. Muhammed</h2><p>Sıdk, Emanet</p><h3>Kureyş Suresi</h3><p>Ticaret</p>`, summary: `<h2>Özet</h2><p>Emin</p>`, tips: `<h2>İpucu</h2><p>İstişare</p>`, mistakes: `<h2>Dikkat</h2><p>İnsan</p>`, questions: [{ id: 531, text: "Güvenilir?", options: ["Sıdk", "Emanet", "Fetanet", "Tebliğ"], correct: 1 }], game: { type: "matching", pairs: [{ text: "Emin", match: "Güvenilir" }] } } },
            { id: "kuran", title: "5. Kur'an-ı Kerim", content: { lecture: `<h2>Kur'an</h2><p>114 Sure</p><h3>Hz. Nuh</h3><p>950 yıl</p>`, summary: `<h2>Özet</h2><p>Ayet, Sure, Cüz</p>`, tips: `<h2>İpucu</h2><p>İlk Alak</p>`, mistakes: `<h2>Dikkat</h2><p>Tüm insanlığa</p>`, questions: [{ id: 541, text: "En kısa sure?", options: ["Kevser", "İhlas", "Fatiha", "Bakara"], correct: 0 }], game: { type: "matching", pairs: [{ text: "Ayet", match: "Cümle" }] } } }
        ]
    }
};
